(function(){
'use strict';
const $=id=>document.getElementById(id);let currentUser=null;let currentPage='home';let products=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(t,ok=false){$('authMessage').textContent=t||'';$('authMessage').className='message '+(ok?'success':'');}
function displayName(user){return user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Usuário';}
function showApp(){ $('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('userName').textContent='Olá, '+displayName(currentUser)+'!';$('userEmail').textContent=currentUser.email||'';render(); }
function render(){document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));$('page').innerHTML=currentPage==='home'?homePage():productsPage();bindPage();}
function homePage(){const today=new Date().toLocaleDateString('pt-BR');return `<section class="hero"><div class="eyebrow">VISÃO GERAL</div><h1>Olá, ${esc(displayName(currentUser))}! Vamos cuidar das suas atividades?</h1><p>Organize seus produtos, acompanhe suas ações e mantenha sua operação em dia.</p><span class="status-pill">● Sistema conectado</span></section><section class="stats"><article><span class="stat-icon">▣</span><strong>${products.length}</strong><b>Produtos cadastrados</b><small>Registros vinculados ao seu usuário</small></article><article><span class="stat-icon blue">◷</span><strong>${products.filter(p=>p.status==='pendente').length}</strong><b>Pendentes</b><small>Ações que precisam de acompanhamento</small></article><article><span class="stat-icon green">✓</span><strong>${products.filter(p=>p.status==='concluido').length}</strong><b>Concluídos</b><small>Atividades finalizadas</small></article></section><section class="panel"><div class="panel-heading"><div><div class="eyebrow">ATIVIDADE</div><h2>Resumo de hoje</h2></div><button class="primary" data-go="products">Ver produtos</button></div><p class="muted">${today} · Seu painel inicial está conectado à nuvem.</p><div class="empty">Use a página Produtos para cadastrar os itens da sua operação.</div></section>`;}
function productsPage(){return `<section class="hero compact"><div class="eyebrow">OPERAÇÃO</div><h1>Produtos</h1><p>Cadastre e acompanhe os produtos vinculados ao seu acesso.</p></section><section class="panel"><div class="panel-heading"><div><div class="eyebrow">CATÁLOGO</div><h2>Seus produtos</h2></div><button class="primary" id="openAdd">+ Adicionar</button></div><div id="productFormWrap" class="form-wrap hidden"><form id="productForm"><label>Nome do produto<input id="productName" required maxlength="120" placeholder="Ex.: Produto demonstrativo"></label><label>EAN / código<input id="productEan" maxlength="30" placeholder="Opcional"></label><label>Marca / empresa<input id="productBrand" maxlength="100" placeholder="Marca ou empresa"></label><label>Status<select id="productStatus"><option value="pendente">Pendente</option><option value="concluido">Concluído</option></select></label><div class="form-actions"><button type="button" class="secondary" id="cancelAdd">Cancelar</button><button class="primary" type="submit">Salvar na nuvem</button></div><p id="productMessage" class="message"></p></form></div><div id="productsList">${productRows()}</div></section>`;}
function productRows(){if(!products.length)return '<div class="empty">Nenhum produto cadastrado ainda.</div>';return '<div class="product-list">'+products.map(p=>`<article class="product-row"><div class="product-icon">📦</div><div><strong>${esc(p.name)}</strong><small>${esc(p.brand||'Marca não informada')} · ${esc(p.ean||'EAN não informado')}</small><span class="tag">${esc(p.status||'pendente')}</span></div></article>`).join('')+'</div>';}
function bindPage(){document.querySelectorAll('[data-go="products"]').forEach(b=>b.onclick=()=>{currentPage='products';render();});$('openAdd')?.addEventListener('click',()=>{$('productFormWrap').classList.remove('hidden');$('openAdd').classList.add('hidden');});$('cancelAdd')?.addEventListener('click',()=>{render();});$('productForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('productMessage');msg.textContent='Salvando...';try{await PromotorSupabase.addProduct({name:$('productName').value.trim(),ean:$('productEan').value.trim()||null,brand:$('productBrand').value.trim()||null,status:$('productStatus').value,user_id:currentUser.id});products=await PromotorSupabase.listProducts();render();}catch(err){msg.textContent='Não foi possível salvar: '+(err.message||err);}});}
async function loadProducts(){try{products=await PromotorSupabase.listProducts();}catch(err){products=[];console.warn(err);}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginButton').disabled=true;message('Validando acesso na nuvem...');try{const data=await PromotorSupabase.signIn($('email').value.trim(),$('password').value);currentUser=data.user;await loadProducts();showApp();}catch(err){message(err.message||'Não foi possível entrar.');}finally{$('loginButton').disabled=false;}});
$('resetButton').addEventListener('click',async()=>{const email=$('email').value.trim();if(!email){message('Informe seu e-mail para recuperar a senha.');return;}try{await PromotorSupabase.resetPassword(email);message('Link de recuperação enviado. Confira seu e-mail.',true);}catch(err){message(err.message||'Não foi possível enviar o link.');}});
$('menuButton').addEventListener('click',()=>{$('navPanel').classList.toggle('open');});document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.addEventListener('click',()=>{currentPage=b.dataset.page;$('navPanel').classList.remove('open');render();}));$('logoutButton').addEventListener('click',async()=>{await PromotorSupabase.signOut();location.reload();});
(async()=>{try{const session=await PromotorSupabase.session();if(session?.user){currentUser=session.user;await loadProducts();showApp();}}catch(err){console.warn(err);}})();
})();
