(function(){
'use strict';
const $=id=>document.getElementById(id);
let currentUser=null;
let currentPage='home';
let products=[];
let scannerStream=null;
let profile=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(t,ok=false){$('authMessage').textContent=t||'';$('authMessage').className='message '+(ok?'success':'');}
function displayName(user){return user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'Usuário';}
function showApp(){ $('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('userName').textContent='Olá, '+displayName(currentUser)+'!';$('userEmail').textContent=(profile?.company?profile.company+' · ':'')+(currentUser.email||'');render(); }
function render(){document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));$('page').innerHTML=currentPage==='home'?homePage():productsPage();bindPage();}
function homePage(){const today=new Date().toLocaleDateString('pt-BR');return `<section class="hero"><div class="eyebrow">VISÃO GERAL</div><h1>Olá, ${esc(displayName(currentUser))}! Vamos cuidar das suas atividades?</h1><p>Organize seus produtos, acompanhe suas ações e mantenha sua operação em dia.</p><span class="status-pill">● Sistema conectado</span></section><section class="stats"><article><span class="stat-icon">▣</span><strong>${products.length}</strong><b>Produtos cadastrados</b><small>Registros vinculados ao seu usuário</small></article><article><span class="stat-icon blue">◷</span><strong>${products.filter(p=>p.status==='pendente').length}</strong><b>Pendentes</b><small>Ações que precisam de acompanhamento</small></article><article><span class="stat-icon green">✓</span><strong>${products.filter(p=>p.status==='concluido').length}</strong><b>Concluídos</b><small>Atividades finalizadas</small></article></section><section class="panel"><div class="panel-heading"><div><div class="eyebrow">ATIVIDADE</div><h2>Resumo de hoje</h2></div><button class="primary" data-go="products">Ver produtos</button></div><p class="muted">${today} · Seu painel inicial está conectado à nuvem.</p><div class="empty">Use a página Produtos para cadastrar os itens da sua operação.</div></section>`;}
function productsPage(){return `<section class="hero compact"><div class="eyebrow">OPERAÇÃO</div><h1>Produtos</h1><p>Cadastre e acompanhe os produtos vinculados ao seu acesso.</p></section><section class="panel"><div class="panel-heading"><div><div class="eyebrow">CATÁLOGO</div><h2>Seus produtos</h2></div><button class="primary" id="openAdd">+ Adicionar produto</button></div><div id="productsList">${productRows()}</div></section><div id="productModal" class="modal-backdrop hidden" role="dialog" aria-modal="true" aria-labelledby="productModalTitle"><div class="modal-card"><button class="modal-close" id="closeProductModal" aria-label="Fechar">×</button><div class="eyebrow">CADASTRO</div><h2 id="productModalTitle">Novo produto</h2><p class="modal-subtitle">Registre o produto no catálogo do Promotor PA.</p><form id="productForm"><label>Nome do produto<input id="productName" required maxlength="120" placeholder="Ex.: Leite Ninho 750g"></label><div class="field-row"><label>EAN / código de barras<div class="inline-field"><input id="productEan" maxlength="30" placeholder="Digite ou leia o EAN"><button type="button" class="secondary compact-btn" id="scanEan">▣ Ler</button><button type="button" class="secondary compact-btn" id="findEan">⌕ Buscar</button></div></label></div><label>Foto do produto<input id="productPhoto" type="file" accept="image/*"><small class="field-help">Opcional · JPG, PNG ou WEBP até 5 MB.</small></label><div class="field-row two"><label>Local<select id="productLocation" required><option value="Sessão">Sessão</option><option value="Deposito">Deposito</option></select></label><label>Validade<input id="productExpiration" type="date"></label></div><div class="field-row two"><label>Quantidade<input id="productQuantity" type="number" min="0" step="1" value="1" required></label><label>Status<select id="productStatus"><option value="pendente">Pendente</option><option value="concluido">Concluído</option></select></label></div><div class="form-actions"><button type="button" class="secondary" id="cancelAdd">Cancelar</button><button class="primary" type="submit" id="saveProduct">Salvar produto</button></div><p id="productMessage" class="message" role="status"></p></form></div></div><div id="scannerModal" class="modal-backdrop hidden" role="dialog" aria-modal="true"><div class="modal-card scanner-card"><button class="modal-close" id="closeScanner" aria-label="Fechar">×</button><div class="eyebrow">LEITOR</div><h2>Ler código de barras</h2><video id="scannerVideo" autoplay playsinline></video><p id="scannerMessage" class="message">Aponte a câmera para o código de barras.</p><button class="secondary wide" id="stopScanner" type="button">Fechar leitor</button></div></div>`;}
function productRows(){if(!products.length)return '<div class="empty">Nenhum produto cadastrado ainda.</div>';return '<div class="product-list">'+products.map(p=>`<article class="product-row"><div class="product-icon">📦</div><div class="product-main"><strong>${esc(p.name)}</strong><small>${esc(p.company||profile?.company||'Empresa não informada')} · ${esc(p.ean||'EAN não informado')}</small><small>Local: ${esc(p.location||'Não informado')} · Qtd.: ${esc(p.quantity??0)}${p.expiration_date?' · Validade: '+esc(formatDate(p.expiration_date)):''}</small><span class="tag">${esc(p.status||'pendente')}</span></div></article>`).join('')+'</div>';}
function formatDate(value){if(!value)return '';const [y,m,d]=String(value).slice(0,10).split('-');return d&&m&&y?`${d}/${m}/${y}`:value;}
function openProductModal(){const modal=$('productModal');modal.classList.remove('hidden');$('productName').focus();}
function closeProductModal(){stopScanner();$('productModal')?.classList.add('hidden');}
async function startScanner(){if(!('BarcodeDetector' in window)){ $('productMessage').textContent='Seu navegador não oferece leitura automática. Digite o EAN e use Buscar.';return;}try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('scannerVideo').srcObject=scannerStream;$('scannerModal').classList.remove('hidden');const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']});const scan=async()=>{if(!scannerStream||$('scannerModal').classList.contains('hidden'))return;try{const codes=await detector.detect($('scannerVideo'));if(codes.length){$('productEan').value=codes[0].rawValue||'';stopScanner();await findExistingEan();return;}}catch(e){}requestAnimationFrame(scan);};requestAnimationFrame(scan);}catch(err){$('productMessage').textContent='Não foi possível abrir a câmera. Confira a permissão do navegador.';}}
function stopScanner(){if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null;}if($('scannerVideo'))$('scannerVideo').srcObject=null;$('scannerModal')?.classList.add('hidden');}
async function findExistingEan(){const ean=$('productEan').value.trim();if(!ean){$('productMessage').textContent='Informe um EAN para buscar.';return;}const local=products.find(p=>String(p.ean||'')===ean);if(local){$('productName').value=local.name||'';$('productLocation').value=local.location||'Sessão';$('productMessage').textContent='Dados encontrados no seu catálogo. Confira antes de salvar.';return;}const button=$('findEan');button.disabled=true;$('productMessage').textContent='Buscando na nuvem e no catálogo público...';try{const result=await PromotorSupabase.lookupBarcode(ean);if(!result){$('productMessage').textContent='Nenhum produto encontrado para este EAN. Confira o código ou preencha o nome manualmente.';return;}$('productName').value=result.name||'';$('productMessage').textContent='Produto encontrado na base pública. Confira os dados antes de salvar.';}catch(err){$('productMessage').textContent='Não foi possível consultar o EAN agora. Você pode preencher o nome manualmente.';}finally{button.disabled=false;}}
function bindPage(){document.querySelectorAll('[data-go="products"]').forEach(b=>b.onclick=()=>{currentPage='products';render();});$('openAdd')?.addEventListener('click',openProductModal);$('closeProductModal')?.addEventListener('click',closeProductModal);$('cancelAdd')?.addEventListener('click',closeProductModal);$('scanEan')?.addEventListener('click',startScanner);$('findEan')?.addEventListener('click',findExistingEan);$('closeScanner')?.addEventListener('click',stopScanner);$('stopScanner')?.addEventListener('click',stopScanner);$('productForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('productMessage');const save=$('saveProduct');save.disabled=true;msg.textContent='Salvando na nuvem...';try{const file=$('productPhoto').files?.[0]||null;if(file&&file.size>5*1024*1024)throw new Error('A foto deve ter no máximo 5 MB.');const photoUrl=file?await PromotorSupabase.uploadProductPhoto(file,currentUser.id):null;await PromotorSupabase.addProduct({name:$('productName').value.trim(),ean:$('productEan').value.trim()||null,company:profile?.company||null,location:$('productLocation').value,expiration_date:$('productExpiration').value||null,quantity:Number($('productQuantity').value||0),status:$('productStatus').value,user_id:currentUser.id,photo_url:photoUrl});products=await PromotorSupabase.listProducts();closeProductModal();render();}catch(err){msg.textContent='Não foi possível salvar: '+(err.message||err);}finally{save.disabled=false;}});}
async function loadProducts(){try{products=await PromotorSupabase.listProducts();}catch(err){products=[];console.warn(err);}}
async function loadProfile(){profile=await PromotorSupabase.getProfile(currentUser.id);}
async function registerUser(){const name=$('registerName').value.trim(),company=$('registerCompany').value.trim(),email=$('registerEmail').value.trim(),password=$('registerPassword').value,confirm=$('registerConfirm').value;if(password!==confirm)throw new Error('As senhas não coincidem.');if(password.length<6)throw new Error('A senha deve ter pelo menos 6 caracteres.');const data=await PromotorSupabase.signUp({email,password,full_name:name,company});if(data.user){currentUser=data.user;await loadProfile();if(data.session){await loadProducts();showApp();}else{message('Cadastro realizado. Confirme seu e-mail para entrar.',true);$('registerForm').classList.add('hidden');$('loginForm').classList.remove('hidden');}}}
$('showRegister').addEventListener('click',()=>{$('loginForm').classList.add('hidden');$('registerForm').classList.remove('hidden');$('authTitle').textContent='Criar acesso';});$('showLogin').addEventListener('click',()=>{$('registerForm').classList.add('hidden');$('loginForm').classList.remove('hidden');$('authTitle').textContent='Bem-vindo!';});$('registerForm').addEventListener('submit',async e=>{e.preventDefault();$('registerButton').disabled=true;message('Criando seu acesso na nuvem...');try{await registerUser();}catch(err){message(err.message||'Não foi possível concluir o cadastro.');}finally{$('registerButton').disabled=false;}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginButton').disabled=true;message('Validando acesso na nuvem...');try{const data=await PromotorSupabase.signIn($('email').value.trim(),$('password').value);currentUser=data.user;await loadProfile();await loadProducts();showApp();}catch(err){message(err.message||'Não foi possível entrar.');}finally{$('loginButton').disabled=false;}});
$('resetButton').addEventListener('click',async()=>{const email=$('email').value.trim();if(!email){message('Informe seu e-mail para recuperar a senha.');return;}try{await PromotorSupabase.resetPassword(email);message('Link de recuperação enviado. Confira seu e-mail.',true);}catch(err){message(err.message||'Não foi possível enviar o link.');}});
$('menuButton').addEventListener('click',()=>{$('navPanel').classList.toggle('open');});document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.addEventListener('click',()=>{currentPage=b.dataset.page;$('navPanel').classList.remove('open');render();}));$('logoutButton').addEventListener('click',async()=>{await PromotorSupabase.signOut();location.reload();});
(async()=>{try{const session=await PromotorSupabase.session();if(session?.user){currentUser=session.user;await loadProfile();await loadProducts();showApp();}}catch(err){console.warn(err);}})();
})();
